### ISSUE TITLE
Use Dep-11 YAML format instead

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-appstream-data#1]
Debian guys have proposed a YAML-based Dep-11 format for AppStream, which is now upstream. Compared to XML, YAML is much lighter and contains less BS.

https://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html

**Comment by MingcongBai** [comment]
It's not compatible with RPM repositories though, and we would be obliged to use their screenshot repository (which sucks too hard to believe). I will stay with upstream, XML being your personal dislike is not a valid reason to switch.
